### ISSUE TITLE
Link to source

### ISSUE THREAD

**Issue by olafveerman** [openaq/openaq.github.io#101]
v2 feedback reported by @RocketD0g:

> I notice when the 'airnow' source is clicked on a 'location' or 'country' page, it goes to a forbidden page. I realize it's going to the ftp site for airnow, and that is probably why, since I'm not logged in, but is there any way it can redirect to airnow.gov?

**Comment by olafveerman** [comment]
The source definitions contain two different URLs:

``` json
    {
        "url": "ftp.airnowapi.org",
        "adapter": "airnow",
        "name": "AirNow",
        "city": "",
        "country": "",
        "description": "",
        "sourceURL": "http://www.airnow.gov/",
        "contacts": [
            "info@openaq.org"
        ]
    }
```

`url` - which we are using - usually points to a more precise location of the data. The `sourceURL` usually to some sort of landing page of the organization.

The easiest fix would be to use `sourceURL` instead.

Thoughts @ascalamogna @danielfdsilva @RocketD0g @jflasher ?

**Comment by jflasher** [comment]
@olafveerman 👍 yep, that's intended use. Though because they're named so poorly, I always mix them up :)

**Comment by RocketD0g** [comment]
I can't see a problem with using  sourceURL instead...others?
