### ISSUE TITLE
Dots overflow on left side of time-slider

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq.github.io#102]
On Compare page
Chrome v52.0.2743.116 on OSX 10.11.6
![](https://www.dropbox.com/s/js0exirvo4qpro7/Screenshot%202016-08-31%2011.13.26.png?dl=1)

**Comment by danielfdsilva** [comment]
@jflasher what locations are you comparing?

**Comment by jflasher** [comment]
![](https://www.dropbox.com/s/p14p2pbtesp6fz4/Screenshot%202016-09-01%2011.54.17.png?dl=1)

Happens in a number of places when viewing the charts.

**Comment by jflasher** [comment]
Just checked my console log and I do see this

<img width="1234" alt="screen shot 2016-09-01 at 11 55 46 am" src="https://cloud.githubusercontent.com/assets/848934/18174311/162042c6-703b-11e6-9dd6-e5d2252a22c2.png">

so maybe it's a sizing/resize issue? Don't see same behavior on Firefox. So this may go away when we put on staging (which has SSL cert).

**Comment by danielfdsilva** [comment]
The problem with this is the inconsistent date parsing between browsers.
Firefox interprets the string as being in the current timezone while chrome interprets it as being utc. So:
Date: 2016-08-25T14:00:00
Firefox result: Thu Aug 25 2016 14:00:00 GMT-0400 (EDT)
Chrome result: Thu Aug 25 2016 10:00:00 GMT-0400 (EDT)

Fixed it by using moment.js
