### ISSUE TITLE
unique urls have spaces

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq.github.io#122]
The unique url functionality for pages like the 'comparisons' one is awesome. The only thing is, because spaces appear, the url will not link properly in twitter or facebook. To get around that, I tried shortening it with tinyurl.com, but it will not accept it, either. 
bitly.com will, but it's an unideal workaround.

Here's an example url: 
https://openaq.org/#/compare/Camden Kerbside/MNB/US Diplomatic Post: Pristina?parameter=pm25&_k=huwix6

**Comment by jflasher** [comment]
@danielfdsilva maybe we just urlencode everything before updating location? Will look ugly but should work fine I think.

**Comment by jflasher** [comment]
@RocketD0g should also note if this is something you need to fix now, you can replace spaces with %20 like

https://openaq.org/#/compare/Camden Kerbside/MNB/US%20Diplomatic%20Post:%20Pristina?parameter=pm25
