### ISSUE TITLE
Styling slightly off on some pages

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq.github.io#130]
Assume it's related to our most contentious PR ever https://github.com/openaq/openaq.github.io/pull/129. 

I took a quick look at the site and figured it'd be all broken or not, but looks like some things are slightly off?

https://openaq.org/#/compare/Mandir%20Marg/FRANCONIA/Beijing%20US%20Embassy?parameter=pm25&_k=xoj1qk
![](https://www.dropbox.com/s/xlwx4yy5pjig04e/Screenshot%202016-10-31%2010.10.12.png?dl=1)

cc/ @olafveerman @danielfdsilva

**Comment by RocketD0g** [comment]
Noticed the formatting on the data/country page here too: 

![screen shot 2016-10-31 at 10 15 27 am](https://cloud.githubusercontent.com/assets/13404290/19857164/16d0a1ba-9f53-11e6-8b2b-98d0e4120d0c.png)

**Comment by olafveerman** [comment]
Yup, you're right. It's indeed related to that one PR.
I'll issue a fix soon

**Comment by olafveerman** [comment]
Addressed in this PR https://github.com/openaq/openaq.github.io/pull/133
