### ISSUE TITLE
Have more tutorials of how to use the API

### ISSUE THREAD

**Issue by masalmon** [openaq/openaq.github.io#46]
On the about page here <https://openaq.org/#/about> there's a link to Accessing a Playground of Air Quality Data 

Maybe it could now include links to the interface and the Python and R packages?

I'd even suggest a "Tutorials" tab with how-to's for the three of them, and for the API itself (as in the Medium article), etc. Well for the R package I'd simply have to provide a html version of my vignettes, which is very easy to do.

**Comment by RocketD0g** [comment]
Added link to '[OpenAQ Community Toolbox](https://medium.com/@openaq/tools-built-by-the-openaq-community-857a82ad9ca9#.j45qea590)' post to [About ](https://openaq.org/#/about) and [Sources](https://openaq.org/#/sources) pages, citing @dolugen's OpenAQ Browser, @masalmon's Ropenaq pkg and David Hagan's openaq-py pkg. More can always be added but closing issue for now.

**Comment by masalmon** [comment]
Cool! I'm going to change the R package name to all lower-case today ("ropenaq") but Github will make a redirection.
