### ISSUE TITLE
Put "latest" values on the home page

### ISSUE THREAD

**Issue by masalmon** [openaq/openaq.github.io#49]
To show off!

**Comment by jflasher** [comment]
@masalmon can you give a bit more detail about what this might look like? Do you mean the actual measurement values? 

I've been thinking the homepage would be a map of all the locations (with coords) and their latest values that you could switch between the different pollutants. I've got a bunch of this work done on the `map` branch, just not finished yet.

**Comment by masalmon** [comment]
I had nothing specific in mind, I just thought that showing current values would be cool. A map would be terrific! I guess I can close this now ;-)

**Comment by jflasher** [comment]
Here are a couple screenshots of what I've got so far, still need to figure out a few things, but it's getting there.

![](https://www.dropbox.com/s/bnxdbcdxtmeq1l9/Screenshot%202016-02-24%2009.36.45.png?dl=1)
![](https://www.dropbox.com/s/7im2fc1ssjmjn60/Screenshot%202016-02-24%2009.37.19.png?dl=1)

**Comment by masalmon** [comment]
That looks great! But is it gonna take the whole homepage? Won't it be messy? Or when you open the page you first need to click to see this?

**Comment by jflasher** [comment]
My thought was that it'd be the whole homepage as I think it's the view people would most like to see.

**Comment by masalmon** [comment]
But maybe a "static" part above, like a ribbon, with basic info, would be useful? Or the same as your screenshot but with About/Info/etc not on the map (hard to see them since they're on the map?)

**Comment by masalmon** [comment]
It's just that when I arrive on e.g. aqicn.org I find it quite messy and nothing tells me what aqicn.org is. Right now it is cool to see "Building the first open, real-time air quality data hub for the world." for OpenAQ: :-)

**Comment by masalmon** [comment]
I've just learnt how to use Leaflet for R and I was wondering which language/tool you use for generating the map, @jflasher ?

**Comment by jflasher** [comment]
@masalmon the map is using [mapbox-gl](https://www.mapbox.com/maps/) and we're using JavaScript to control it within the page. Leaflet is very awesome and well worth learning for geospatial data!

**Comment by masalmon** [comment]
Ok thanks for the answer!

I didn't even have to really learn leaflet, the R package is super easy to use!
