### ISSUE TITLE
Create copy for Sources page

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq.github.io#5]
![](https://www.dropbox.com/s/dbh5eesb0m6t209/Screenshot%202015-08-25%2017.39.52.png?dl=1)

**Comment by RocketD0g** [comment]
General Feedback on Cards: 
* Alphabetize the sources by country level, then city level, then by station level. 
* Capitalize PM, NO, etc. 
* For PM25, use PM2.5. 
* Under each sources card, for each discrete source, put "Resolution:" parameter
