### ISSUE TITLE
*Not* using averages calculated from the data for visualizations...yet?

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq.github.io#70]
@olafveerman, I put the comment here instead of the data format area - seemed more fitting? Let me know if you/anyone feels it would go better elsewhere after checking it out.

**Why *not* using averages calc'ed from data right now could be a good idea:**
I think, in the short term, we may want to stay away from generating averages (e.g. weekly, monthly, daily-unless the raw data is shared that way, etc.)  from data aggregated to OpenAQ. It seems like it would be a ton simpler for us at this stage. And I think it puts us in tricky waters to do correctly or even completely transparently, given a) it's a bit out of our scope to properly perform QA/QC, b) we aren't always clear on some of the whole time average/reporting interval thing from the sources themselves, c) would have to come up with other criteria to begin to do this (e.g. for a given time interval, do we need 70% of data reporting? 80%? 50%?), and d) as @olafveerman, some of this meta data, even if we have it captured, is hard-coded in and could change over time. 

For that reason, perhaps we just stick to visualizing the data as it is. I think as others do use the data besides us and publish it in peer-reviewed forums, etc., we can see what people converge upon for good practices with this kind of data aggregated in this manner. Or we can eventually decide to come up with a way to do this ourselves. But perhaps not worry about it now, at this stage.

**The cons to this:**
I personally think that averages of our data over varying time intervals will be some of the most important and interesting stuff that comes out of our platform. It sounded like several users though that too? 

**What not using averages at this time could mean for capturing the historical data on a map**
I know for the map, the idea is to show data historically, and averages are one way to do that. And obviously my video idea of showing a timelapse of how data changes over time also wasn't really feasible. 

But what about just letting click a specific time to show? Just making up a way to do that for the sake of illustration (and in no way implying this is a particularly good way to do this), but imagine a calendar and a clock icon that let you pick a date and time. So maybe I click through different dates at the same time every day, and I see, by eye, how the map changes. Or I do the converse, and stay at the same date, but click through the different hours of the day on a single day. 

**Thoughts about staying away from long-term averaging for now?** 
And/or thoughts about how to still capture historical data on the map and not doing the weekly, monthly, x-ly averaging?

cc: @olafveerman @ascalamogna @danielfdsilva @jflasher

**Comment by jflasher** [comment]
I like the idea of not doing the averages right now, think it frees up some time to think about some of the other items. I think it'll also simplify the frontend a bit. I think being able to pick a certain point in time for the map would be great too. For the API, we currently do a date range, so there'd be a little code weirdness to get the value at one particular time, but it could be done, if that's what we wanted to go with.

**Comment by olafveerman** [comment]
Yes, same here. It will allow us to focus on other elements in the re-design.

**Comment by RocketD0g** [comment]
Awesome, sounds good and thanks!
