### ISSUE TITLE
Feature Analysis and Wireframes

### ISSUE THREAD

**Issue by ascalamogna** [openaq/openaq.github.io#72]
As part of the redesign of OpenAQ we've completed a feature analysis and wireframes.

**Feature Analysis**
This includes functional aspects of our product and other relevant examples to serve as reference points. 

[OpenAQ-Feature Analysis.pdf](https://github.com/openaq/openaq.github.io/files/341456/OpenAQ-Feature.Analysis.pdf)

**Wireframes**
Wireframes are the structure or base of a website. They are built to ensure all parts and functionality are accounted for before design starts. Wireframes are devoid of any design, colors, photos. Again, these are not the final designs but a blueprint for the site.

[wireframes_v4.pdf](https://github.com/openaq/openaq.github.io/files/341455/wireframes_v4.pdf)

**Comment by danielfdsilva** [comment]
V2 ready
