### ISSUE TITLE
Map Design & Interactivity

### ISSUE THREAD

**Issue by DylanMoriarty** [openaq/openaq.github.io#74]
## Basemap Style

<img width="1087" alt="screenshot 2016-07-22 19 13 34" src="https://cloud.githubusercontent.com/assets/9341928/17073626/62f88470-5040-11e6-8562-9854ed1c6329.png">

The basemap style can be [viewed here](https://api.mapbox.com/styles/v1/devseed/ciqs29d060000clnr9222bg5x.html?title=true&access_token=pk.eyJ1IjoiZGV2c2VlZCIsImEiOiJnUi1mbkVvIn0.018aLhX0Mb0tdtaT2QNe2Q#6.700605352844815/38.01937586879359/-77.47950105418056/0).

We wanted to keep it subtle, light to match the site's air-y theme and lighter also to help the data on top pop.

## Color Scale

Currently the scale for showing how much substance is in the air is a divergent scale going from blue to red. This implies left values are 'good' and one's further to the right are 'bad', and that there's a turning point in the middle. We also want to avoid associating the values with those sorts of connotations.

A sequential color scheme helps alleviate that quite a bit. It also thematically makes sense associating the darker more full colored points with 'more of _x_ in the air'. Here are a couple color schemes to consider,

<img width="492" alt="screenshot 2016-07-22 19 09 55" src="https://cloud.githubusercontent.com/assets/9341928/17073572/f5b6daf6-503f-11e6-9f5e-9e4e61ae2de6.png">

<img width="493" alt="screenshot 2016-07-22 19 10 23" src="https://cloud.githubusercontent.com/assets/9341928/17073573/f7d837bc-503f-11e6-9027-35dae39dbd8c.png">

The later option was created because on OpenAQ the majority of points are going to be on the lefthand side. To make sure they still pop, we thought it the scale might need to start a shade or so darker. This part is still under exploration.

## Selected data

To help kick up a point when it's selected, the point will get a white halo and slight shadow.

<img width="373" alt="screenshot 2016-07-22 19 00 40" src="https://cloud.githubusercontent.com/assets/9341928/17073403/a1dff166-503e-11e6-97d7-aeceb8dc2d23.png">

This style can also be replicated on the individual station pages to make clear which point is being analyzed.

<img width="502" alt="screenshot 2016-07-22 19 07 02" src="https://cloud.githubusercontent.com/assets/9341928/17073533/995f162e-503f-11e6-9630-93963b4aa197.png">

@ascalamogna @olafveerman

**Comment by jflasher** [comment]
Awesome, thanks!

**Comment by danielfdsilva** [comment]
Implemented
